### ISSUE TITLE
Setup basic client to talk to the backend

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/Tello-Recon#1]
## Summary of issue
We need to set up a basic frontend/client to talk to the backend of the app- 
This won't include any functionality but should be a functional React-app that has routing for the pages we'll need and slots for the control components that we'll implement later.

## Todo's
- [ ] Implement Home Page: This will display the drone's video feed and allow you to control it/record routins
- [ ] Implement Routines Page: This will allow you to see pre-recorded routines, and upload your own for use. 
- [ ] Implement Settings page: for drone set up and connection

**Comment by MykalMachon** [comment]
this was closed by #7
