### ISSUE TITLE
Setup Drone Controls in Frontend

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/Tello-Recon#5]
## Summary of Issue
We need a "controller" in the frontend of the site to control the drone. 

## Todo's 
- [ ] Determine what V1 of this looks like (i.e do we have arrow key/ wasd support? do we simply have dropdowns and distances "forward, 100cm", etc)
- [ ] Implement the buttons into the frontend on the homepage
- [ ] Ensure controls are sending out commands to the backend (we should probably use [socket.io/websockets](https://socket.io/docs/v3) for this so that as soon as the user releases a key, the drone stops, etc)
- [ ] testing

**Comment by MykalMachon** [comment]
This is done!
